Period service
GrEFeRFeeD/intellistart-java-2022-oneweek pull request #17
Opened 2022-10-14 19:22 UTC by makskostyshen

2022-10-17 07:40 UTC, GrEFeRFeeD commented on src/main/java/com/intellias/intellistart/interviewplanning/model/period/services/validation/chain/LimitsValidator.java
> +    else if (hour < 22){
Use guard clause

2022-10-17 07:42 UTC, GrEFeRFeeD commented on src/test/java/com/intellias/intellistart/interviewplanning/model/period/services/OverlapServiceTest.java
> +    Period p2 = new Period();
You can add @BeforeEach initializing of p1 and p2.

2022-10-17 07:42 UTC, GrEFeRFeeD commented on src/test/java/com/intellias/intellistart/interviewplanning/model/period/services/TimeConverterTest.java
> +    converter.convert("19:23");
No assert methods?

2022-10-17 07:43 UTC, GrEFeRFeeD requested changes
Tests are failed.

2022-10-17 07:44 UTC, makskostyshen commented on src/test/java/com/intellias/intellistart/interviewplanning/model/period/services/TimeConverterTest.java
> +    converter.convert("19:23");
Yes. I check for not throwing exception

2022-10-17 07:48 UTC, makskostyshen commented on pom.xml
> +  </dependencies>
Yes, it was added occasionally when writing tests. The code works without it. I think all checks failed because of this. I'm in the process of investigating.

2022-10-17 07:55 UTC, makskostyshen commented on src/test/java/com/intellias/intellistart/interviewplanning/model/period/services/OverlapServiceTest.java
> +    Period p2 = new Period();
It's a good idea. I can add @beforeeach only for one period, the second one will be changing

2022-10-17 08:02 UTC, GrEFeRFeeD commented on src/test/java/com/intellias/intellistart/interviewplanning/model/period/services/TimeConverterTest.java
> +    converter.convert("19:23");
You can use Assertions.assertDoesNotThrow()

2022-10-17 11:59 UTC, GrEFeRFeeD commented
|File|Coverage [73.1%]|:green_apple:|
|:-|:-:|:-:|
|[CoordinatorController.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/edfd287f086a0888ef6c8fd4f957fe9bc202655f/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2FCoordinatorController.java)|100%|:green_apple:|
|[DurationValidator.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/edfd287f086a0888ef6c8fd4f957fe9bc202655f/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Fperiod%2Fservices%2Fvalidation%2Fchain%2FDurationValidator.java)|100%|:green_apple:|
|[LimitsValidator.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/edfd287f086a0888ef6c8fd4f957fe9bc202655f/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Fperiod%2Fservices%2Fvalidation%2Fchain%2FLimitsValidator.java)|100%|:green_apple:|
|[RoundingValidator.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/edfd287f086a0888ef6c8fd4f957fe9bc202655f/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Fperiod%2Fservices%2Fvalidation%2Fchain%2FRoundingValidator.java)|100%|:green_apple:|
|[PeriodValidator.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/edfd287f086a0888ef6c8fd4f957fe9bc202655f/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Fperiod%2Fservices%2Fvalidation%2FPeriodValidator.java)|100%|:green_apple:|
|[InvalidBoundariesException.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/edfd287f086a0888ef6c8fd4f957fe9bc202655f/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Fperiod%2Fexceptions%2FInvalidBoundariesException.java)|100%|:green_apple:|
|[TimeConverter.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/edfd287f086a0888ef6c8fd4f957fe9bc202655f/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Fperiod%2Fservices%2FTimeConverter.java)|100%|:green_apple:|
|[OverlapService.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/edfd287f086a0888ef6c8fd4f957fe9bc202655f/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Fperiod%2Fservices%2FOverlapService.java)|100%|:green_apple:|
|[Period.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/edfd287f086a0888ef6c8fd4f957fe9bc202655f/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Fperiod%2FPeriod.java)|61.69%|:green_apple:|
|[InterviewPlanningApplication.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/edfd287f086a0888ef6c8fd4f957fe9bc202655f/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2FInterviewPlanningApplication.java)|37.5%|:green_apple:|
|[PeriodService.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/edfd287f086a0888ef6c8fd4f957fe9bc202655f/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Fperiod%2FPeriodService.java)|22.06%|:green_apple:|

|Total Project Coverage|67.52%|:green_apple:|
|:-|:-:|:-:|

2022-10-18 07:45 UTC, GrEFeRFeeD requested changes
1. Put your exceptions to com.intellias.intellistart.intervieweplanning.exceptions package, not com.intellias.intellistart.intervieweplanning.model.period.exceptions.
2. Cover PeriodService with tests using mockings. Your merge request decreases test coverage of project.
3. ChainValidator is not the best naming choice for the interface where you want to test only LocalTime. If such model of validation was chosen it would be better to rename interface LocalTimeChainValidator or make global generalized interface ChainValidator<T> with boolean isNotCorrect(T o1, T o2) or etc.
4. Provide documentation for all of your methods in class (even private methods need it).
5. Is "Optional<Period> findPeriod(LocalTime, LocaTime)" is the best name for a method? Why not findPeriodByFromTo or etc?

2022-10-19 15:53 UTC, GrEFeRFeeD commented
|File|Coverage [86.08%]|:green_apple:|
|:-|:-:|:-:|
|[StartDataLoader.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/310464f0ee434e76bf5f1421af2b0d1db001a7b0/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Finitialization%2FStartDataLoader.java)|100%|:green_apple:|
|[InvalidBoundariesException.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/310464f0ee434e76bf5f1421af2b0d1db001a7b0/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fexceptions%2FInvalidBoundariesException.java)|100%|:green_apple:|
|[CoordinatorController.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/310464f0ee434e76bf5f1421af2b0d1db001a7b0/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2FCoordinatorController.java)|100%|:green_apple:|
|[DurationValidator.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/310464f0ee434e76bf5f1421af2b0d1db001a7b0/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Fperiod%2Fservices%2Fvalidation%2Fchain%2FDurationValidator.java)|100%|:green_apple:|
|[LimitsValidator.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/310464f0ee434e76bf5f1421af2b0d1db001a7b0/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Fperiod%2Fservices%2Fvalidation%2Fchain%2FLimitsValidator.java)|100%|:green_apple:|
|[RoundingValidator.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/310464f0ee434e76bf5f1421af2b0d1db001a7b0/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Fperiod%2Fservices%2Fvalidation%2Fchain%2FRoundingValidator.java)|100%|:green_apple:|
|[PeriodValidator.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/310464f0ee434e76bf5f1421af2b0d1db001a7b0/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Fperiod%2Fservices%2Fvalidation%2FPeriodValidator.java)|100%|:green_apple:|
|[TimeConverter.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/310464f0ee434e76bf5f1421af2b0d1db001a7b0/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Fperiod%2Fservices%2FTimeConverter.java)|100%|:green_apple:|
|[OverlapService.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/310464f0ee434e76bf5f1421af2b0d1db001a7b0/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Fperiod%2Fservices%2FOverlapService.java)|100%|:green_apple:|
|[PeriodService.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/310464f0ee434e76bf5f1421af2b0d1db001a7b0/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Fperiod%2FPeriodService.java)|91.18%|:green_apple:|
|[Period.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/310464f0ee434e76bf5f1421af2b0d1db001a7b0/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Fperiod%2FPeriod.java)|75.32%|:green_apple:|
|[Week.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/310464f0ee434e76bf5f1421af2b0d1db001a7b0/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Fweek%2FWeek.java)|38.75%|:green_apple:|
|[InterviewPlanningApplication.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/310464f0ee434e76bf5f1421af2b0d1db001a7b0/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2FInterviewPlanningApplication.java)|37.5%|:green_apple:|
|[BookingLimit.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/310464f0ee434e76bf5f1421af2b0d1db001a7b0/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Fbookinglimit%2FBookingLimit.java)|36.9%|:green_apple:|

|Total Project Coverage|71.1%|:green_apple:|
|:-|:-:|:-:|

2022-10-19 16:09 UTC, GrEFeRFeeD commented
> * for the rest of my methods, additional documentation is obvious and redundant. To my mind, it's easier to read without it.

Let's discuss this in stand-up.

2022-10-19 16:27 UTC, makskostyshen commented
> > * for the rest of my methods, additional documentation is obvious and redundant. To my mind, it's easier to read without it.
> 
> Let's discuss this in stand-up.

with pleasure)

2022-10-20 15:57 UTC, GrEFeRFeeD commented
|File|Coverage [86.08%]|:green_apple:|
|:-|:-:|:-:|
|[StartDataLoader.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/c82fd8ed9db8889113f86261086057bcb31e15aa/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Finitialization%2FStartDataLoader.java)|100%|:green_apple:|
|[InvalidBoundariesException.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/c82fd8ed9db8889113f86261086057bcb31e15aa/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fexceptions%2FInvalidBoundariesException.java)|100%|:green_apple:|
|[CoordinatorController.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/c82fd8ed9db8889113f86261086057bcb31e15aa/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2FCoordinatorController.java)|100%|:green_apple:|
|[DurationValidator.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/c82fd8ed9db8889113f86261086057bcb31e15aa/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Fperiod%2Fservices%2Fvalidation%2Fchain%2FDurationValidator.java)|100%|:green_apple:|
|[LimitsValidator.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/c82fd8ed9db8889113f86261086057bcb31e15aa/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Fperiod%2Fservices%2Fvalidation%2Fchain%2FLimitsValidator.java)|100%|:green_apple:|
|[RoundingValidator.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/c82fd8ed9db8889113f86261086057bcb31e15aa/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Fperiod%2Fservices%2Fvalidation%2Fchain%2FRoundingValidator.java)|100%|:green_apple:|
|[PeriodValidator.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/c82fd8ed9db8889113f86261086057bcb31e15aa/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Fperiod%2Fservices%2Fvalidation%2FPeriodValidator.java)|100%|:green_apple:|
|[TimeConverter.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/c82fd8ed9db8889113f86261086057bcb31e15aa/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Fperiod%2Fservices%2FTimeConverter.java)|100%|:green_apple:|
|[OverlapService.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/c82fd8ed9db8889113f86261086057bcb31e15aa/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Fperiod%2Fservices%2FOverlapService.java)|100%|:green_apple:|
|[PeriodService.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/c82fd8ed9db8889113f86261086057bcb31e15aa/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Fperiod%2FPeriodService.java)|91.18%|:green_apple:|
|[Period.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/c82fd8ed9db8889113f86261086057bcb31e15aa/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Fperiod%2FPeriod.java)|75.32%|:green_apple:|
|[Week.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/c82fd8ed9db8889113f86261086057bcb31e15aa/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Fweek%2FWeek.java)|38.75%|:green_apple:|
|[InterviewPlanningApplication.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/c82fd8ed9db8889113f86261086057bcb31e15aa/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2FInterviewPlanningApplication.java)|37.5%|:green_apple:|
|[BookingLimit.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/c82fd8ed9db8889113f86261086057bcb31e15aa/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Fbookinglimit%2FBookingLimit.java)|36.9%|:green_apple:|

|Total Project Coverage|71.1%|:green_apple:|
|:-|:-:|:-:|

2022-10-20 18:17 UTC, GrEFeRFeeD approved these changes
Good job.

2022-10-20 18:51 UTC, sonnka approved these changes
Looks nice)

2022-10-20 19:03 UTC, guzeyarthur commented on src/main/java/com/intellias/intellistart/interviewplanning/model/period/services/OverlapService.java
> +@Component
I would prefer to choose the "Service" annotation instead of "Component" because the class is called "OverlapService".

2022-10-20 19:33 UTC, guzeyarthur commented on src/main/java/com/intellias/intellistart/interviewplanning/model/period/services/validation/PeriodValidator.java
> +  private final List<PeriodChainValidator> validators = new ArrayList<>(Arrays.asList(
add the keyword static

2022-10-20 19:33 UTC, guzeyarthur commented on src/main/java/com/intellias/intellistart/interviewplanning/model/period/services/validation/PeriodValidator.java
> +  public void validate(LocalTime from, LocalTime to) {
add the keyword static

2022-10-21 14:45 UTC, makskostyshen commented on src/main/java/com/intellias/intellistart/interviewplanning/model/period/services/OverlapService.java
> +@Component
yep, sounds reasonable

2022-10-21 14:48 UTC, makskostyshen commented on src/main/java/com/intellias/intellistart/interviewplanning/model/period/services/validation/PeriodValidator.java
> +  private final List<PeriodChainValidator> validators = new ArrayList<>(Arrays.asList(
We decided not to use static in validators. I suggest not adding static keyword so far

2022-10-21 19:40 UTC, GrEFeRFeeD commented
|File|Coverage [83.78%]|:green_apple:|
|:-|:-:|:-:|
|[StartDataLoader.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/878ff0a0d24b5a07f3ab6b25505554edeaab58f6/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Finitialization%2FStartDataLoader.java)|100%|:green_apple:|
|[InvalidBoundariesException.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/878ff0a0d24b5a07f3ab6b25505554edeaab58f6/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fexceptions%2FInvalidBoundariesException.java)|100%|:green_apple:|
|[CoordinatorController.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/878ff0a0d24b5a07f3ab6b25505554edeaab58f6/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2FCoordinatorController.java)|100%|:green_apple:|
|[DurationValidator.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/878ff0a0d24b5a07f3ab6b25505554edeaab58f6/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Fperiod%2Fservices%2Fvalidation%2Fchain%2FDurationValidator.java)|100%|:green_apple:|
|[RoundingMinutesValidator.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/878ff0a0d24b5a07f3ab6b25505554edeaab58f6/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Fperiod%2Fservices%2Fvalidation%2Fchain%2FRoundingMinutesValidator.java)|100%|:green_apple:|
|[ExtremeValuesValidator.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/878ff0a0d24b5a07f3ab6b25505554edeaab58f6/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Fperiod%2Fservices%2Fvalidation%2Fchain%2FExtremeValuesValidator.java)|100%|:green_apple:|
|[PeriodValidator.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/878ff0a0d24b5a07f3ab6b25505554edeaab58f6/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Fperiod%2Fservices%2Fvalidation%2FPeriodValidator.java)|100%|:green_apple:|
|[TimeConverter.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/878ff0a0d24b5a07f3ab6b25505554edeaab58f6/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Fperiod%2Fservices%2FTimeConverter.java)|100%|:green_apple:|
|[OverlapService.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/878ff0a0d24b5a07f3ab6b25505554edeaab58f6/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Fperiod%2Fservices%2FOverlapService.java)|100%|:green_apple:|
|[Period.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/878ff0a0d24b5a07f3ab6b25505554edeaab58f6/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Fperiod%2FPeriod.java)|74.03%|:green_apple:|
|[PeriodService.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/878ff0a0d24b5a07f3ab6b25505554edeaab58f6/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Fperiod%2FPeriodService.java)|57.35%|:green_apple:|
|[Week.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/878ff0a0d24b5a07f3ab6b25505554edeaab58f6/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Fweek%2FWeek.java)|38.75%|:green_apple:|
|[InterviewPlanningApplication.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/878ff0a0d24b5a07f3ab6b25505554edeaab58f6/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2FInterviewPlanningApplication.java)|37.5%|:green_apple:|
|[BookingLimit.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/878ff0a0d24b5a07f3ab6b25505554edeaab58f6/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Fbookinglimit%2FBookingLimit.java)|36.9%|:green_apple:|

|Total Project Coverage|69.78%|:green_apple:|
|:-|:-:|:-:|

2022-10-24 19:50 UTC, GrEFeRFeeD commented
|File|Coverage [85.9%]|:green_apple:|
|:-|:-:|:-:|
|[StartDataLoader.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/1b4997f86342c7ebad697da434a2c347763e774c/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Finitialization%2FStartDataLoader.java)|100%|:green_apple:|
|[InvalidBoundariesException.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/1b4997f86342c7ebad697da434a2c347763e774c/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fexceptions%2FInvalidBoundariesException.java)|100%|:green_apple:|
|[CoordinatorController.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/1b4997f86342c7ebad697da434a2c347763e774c/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2FCoordinatorController.java)|100%|:green_apple:|
|[DurationValidator.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/1b4997f86342c7ebad697da434a2c347763e774c/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Fperiod%2Fservices%2Fvalidation%2Fchain%2FDurationValidator.java)|100%|:green_apple:|
|[RoundingMinutesValidator.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/1b4997f86342c7ebad697da434a2c347763e774c/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Fperiod%2Fservices%2Fvalidation%2Fchain%2FRoundingMinutesValidator.java)|100%|:green_apple:|
|[ExtremeValuesValidator.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/1b4997f86342c7ebad697da434a2c347763e774c/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Fperiod%2Fservices%2Fvalidation%2Fchain%2FExtremeValuesValidator.java)|100%|:green_apple:|
|[PeriodValidator.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/1b4997f86342c7ebad697da434a2c347763e774c/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Fperiod%2Fservices%2Fvalidation%2FPeriodValidator.java)|100%|:green_apple:|
|[TimeConverter.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/1b4997f86342c7ebad697da434a2c347763e774c/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Fperiod%2Fservices%2FTimeConverter.java)|100%|:green_apple:|
|[OverlapService.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/1b4997f86342c7ebad697da434a2c347763e774c/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Fperiod%2Fservices%2FOverlapService.java)|100%|:green_apple:|
|[PeriodService.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/1b4997f86342c7ebad697da434a2c347763e774c/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Fperiod%2FPeriodService.java)|91.18%|:green_apple:|
|[Period.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/1b4997f86342c7ebad697da434a2c347763e774c/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Fperiod%2FPeriod.java)|74.03%|:green_apple:|
|[Week.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/1b4997f86342c7ebad697da434a2c347763e774c/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Fweek%2FWeek.java)|38.75%|:green_apple:|
|[InterviewPlanningApplication.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/1b4997f86342c7ebad697da434a2c347763e774c/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2FInterviewPlanningApplication.java)|37.5%|:green_apple:|
|[BookingLimit.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/1b4997f86342c7ebad697da434a2c347763e774c/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Fbookinglimit%2FBookingLimit.java)|36.9%|:green_apple:|

|Total Project Coverage|70.99%|:green_apple:|
|:-|:-:|:-:|

2022-10-24 19:51 UTC, makskostyshen commented
I updated my mock tests to improve coverage. Please look at it

2022-10-24 23:58 UTC, guzeyarthur approved these changes

2022-10-25 06:37 UTC, sashav389 approved these changes

2022-10-25 18:07 UTC, GrEFeRFeeD commented
|File|Coverage [74.46%]|:green_apple:|
|:-|:-:|:-:|
|[InvalidBoundariesException.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/86f6bbc70c053c13f43d78095be09a0bfafead13/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fexceptions%2FInvalidBoundariesException.java)|100%|:green_apple:|
|[CoordinatorController.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/86f6bbc70c053c13f43d78095be09a0bfafead13/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2FCoordinatorController.java)|100%|:green_apple:|
|[DurationValidator.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/86f6bbc70c053c13f43d78095be09a0bfafead13/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Fperiod%2Fservices%2Fvalidation%2Fchain%2FDurationValidator.java)|100%|:green_apple:|
|[RoundingMinutesValidator.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/86f6bbc70c053c13f43d78095be09a0bfafead13/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Fperiod%2Fservices%2Fvalidation%2Fchain%2FRoundingMinutesValidator.java)|100%|:green_apple:|
|[ExtremeValuesValidator.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/86f6bbc70c053c13f43d78095be09a0bfafead13/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Fperiod%2Fservices%2Fvalidation%2Fchain%2FExtremeValuesValidator.java)|100%|:green_apple:|
|[PeriodValidator.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/86f6bbc70c053c13f43d78095be09a0bfafead13/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Fperiod%2Fservices%2Fvalidation%2FPeriodValidator.java)|100%|:green_apple:|
|[OverlapService.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/86f6bbc70c053c13f43d78095be09a0bfafead13/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Fperiod%2Fservices%2FOverlapService.java)|100%|:green_apple:|
|[TimeConverter.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/86f6bbc70c053c13f43d78095be09a0bfafead13/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Fperiod%2Fservices%2FTimeConverter.java)|100%|:green_apple:|
|[PeriodService.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/86f6bbc70c053c13f43d78095be09a0bfafead13/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Fperiod%2FPeriodService.java)|91.18%|:green_apple:|
|[Period.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/86f6bbc70c053c13f43d78095be09a0bfafead13/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Fperiod%2FPeriod.java)|74.03%|:green_apple:|
|[Week.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/86f6bbc70c053c13f43d78095be09a0bfafead13/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Fweek%2FWeek.java)|38.75%|:green_apple:|
|[InterviewPlanningApplication.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/86f6bbc70c053c13f43d78095be09a0bfafead13/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2FInterviewPlanningApplication.java)|37.5%|:green_apple:|
|[BookingLimit.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/86f6bbc70c053c13f43d78095be09a0bfafead13/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Fbookinglimit%2FBookingLimit.java)|36.9%|:green_apple:|

|Total Project Coverage|49.15%|:green_apple:|
|:-|:-:|:-:|

2022-10-25 18:12 UTC, merged