Week service
GrEFeRFeeD/intellistart-java-2022-oneweek pull request #18
Opened 2022-10-17 16:40 UTC by sonnka

2022-10-17 18:14 UTC, makskostyshen commented
Checkstyle tests are failed, please recheck in your IDE

2022-10-18 07:51 UTC, GrEFeRFeeD requested changes
Provide documentation for all of your methods (even private ones need it).

2022-10-18 07:51 UTC, GrEFeRFeeD commented on src/main/java/com/intellias/intellistart/interviewplanning/controllers/GuestController.java
> +@RequestMapping("weeks")
Using one approach for mapping requests would be preferable. Discuss with participants developing CandidateController/InterviewerController about the approach of mapping requests.

2022-10-18 19:16 UTC, GrEFeRFeeD commented
|File|Coverage [89.64%]|:green_apple:|
|:-|:-:|:-:|
|[GuestController.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/552c871fa1ebd29952365661a1cc1e652edcb15c/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2FGuestController.java)|100%|:green_apple:|
|[WeekService.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/552c871fa1ebd29952365661a1cc1e652edcb15c/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Fweek%2FWeekService.java)|88.83%|:green_apple:|

|Total Project Coverage|68.51%|:green_apple:|
|:-|:-:|:-:|

2022-10-19 14:09 UTC, GrEFeRFeeD approved these changes
Seems fine.

2022-10-19 14:25 UTC, sashav389 approved these changes
good work)

2022-10-19 16:25 UTC, makskostyshen requested changes
![1_pravka](https://user-images.githubusercontent.com/82410925/196748449-1b19ecdc-89d1-4aaf-8122-dbb03a2c6e57.png)

- to my opinion, it's worth to refuse from our own DayOfWeek class in favor of embedded java.time.DayOfWeek
- getFromWeekNum() needs refactoring, I think.

2022-10-20 17:30 UTC, GrEFeRFeeD commented
|File|Coverage [90.48%]|:green_apple:|
|:-|:-:|:-:|
|[GuestController.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/ec8073fd48d172b188e04e2ef7c4d388f52a086a/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2FGuestController.java)|100%|:green_apple:|
|[WeekService.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/ec8073fd48d172b188e04e2ef7c4d388f52a086a/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Fweek%2FWeekService.java)|89.8%|:green_apple:|

|Total Project Coverage|68.8%|:green_apple:|
|:-|:-:|:-:|

2022-10-20 18:17 UTC, makskostyshen approved these changes
looks much better

2022-10-20 20:16 UTC, guzeyarthur commented on src/test/java/com/intellias/intellistart/interviewplanning/model/week/WeekServiceTest.java
> +  WeekService weekService = new WeekService(weekRepository);
cut instead of weekService

2022-10-20 20:30 UTC, guzeyarthur commented on src/test/java/com/intellias/intellistart/interviewplanning/model/week/WeekServiceTest.java
> +    assertEquals(expect,result);
"expected" and "actual" instead of "expect,result"

2022-10-20 20:31 UTC, guzeyarthur commented on src/test/java/com/intellias/intellistart/interviewplanning/model/week/WeekServiceTest.java
> +    assertEquals(expect,result);
"expected" and "actual" instead of "expect,result"

2022-10-20 20:39 UTC, guzeyarthur reviewed
Add tests with wrong values. For example, what happens if the convertToLocalDate method includes -133354353 in the weekNum g parameter?

2022-10-20 20:39 UTC, guzeyarthur commented on src/test/java/com/intellias/intellistart/interviewplanning/model/week/WeekServiceTest.java
> +    assertEquals(expect,resultDate);
"expected" and "actual" instead of "expect,result"

2022-10-20 20:39 UTC, guzeyarthur commented on src/test/java/com/intellias/intellistart/interviewplanning/model/week/WeekServiceTest.java
> +    assertEquals(newWeek,captureWeek);
"expected" and "actual"

2022-10-20 20:39 UTC, guzeyarthur commented on src/test/java/com/intellias/intellistart/interviewplanning/model/week/WeekServiceTest.java
> +    assertEquals(expectWeek,newWeek);
"expected" and "actual"

2022-10-20 20:39 UTC, guzeyarthur commented on src/test/java/com/intellias/intellistart/interviewplanning/model/week/WeekServiceTest.java
> +    assertEquals(expectedWeek,newWeek);
"expected" and "actual"

2022-10-21 18:35 UTC, GrEFeRFeeD commented
|File|Coverage [90.48%]|:green_apple:|
|:-|:-:|:-:|
|[GuestController.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/c843989a4e49732e0645b5600fdc503b20318f00/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2FGuestController.java)|100%|:green_apple:|
|[WeekService.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/c843989a4e49732e0645b5600fdc503b20318f00/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Fweek%2FWeekService.java)|89.8%|:green_apple:|

|Total Project Coverage|68.8%|:green_apple:|
|:-|:-:|:-:|

2022-10-24 23:53 UTC, guzeyarthur commented on src/test/java/com/intellias/intellistart/interviewplanning/model/week/WeekServiceTest.java
> +  WeekRepository weekRepository = Mockito.mock(WeekRepository.class);
Add private static

2022-10-24 23:53 UTC, guzeyarthur commented on src/test/java/com/intellias/intellistart/interviewplanning/model/week/WeekServiceTest.java
> +    cut.createWeek(153L);
the call of the method under test must be below verify

2022-10-24 23:53 UTC, guzeyarthur commented on src/test/java/com/intellias/intellistart/interviewplanning/model/week/WeekServiceTest.java
> +    Week actual = cut.getWeekByWeekNum(153L);
the call of the method under test must be below verify

2022-10-24 23:53 UTC, guzeyarthur commented on src/test/java/com/intellias/intellistart/interviewplanning/model/week/WeekServiceTest.java
> +    Week actual = cut.getWeekByWeekNum(153L);
the call of the method under test must be below verify

2022-10-25 19:43 UTC, GrEFeRFeeD commented
|File|Coverage [90.48%]|:green_apple:|
|:-|:-:|:-:|
|[GuestController.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/54e9fcc8f96bd8e1afd163c9d41d3acbdb232311/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2FGuestController.java)|100%|:green_apple:|
|[WeekService.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/54e9fcc8f96bd8e1afd163c9d41d3acbdb232311/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Fweek%2FWeekService.java)|89.8%|:green_apple:|

|Total Project Coverage|53.26%|:green_apple:|
|:-|:-:|:-:|

2022-10-25 19:58 UTC, merged