Interviewer slot integration
GrEFeRFeeD/intellistart-java-2022-oneweek pull request #20
Opened 2022-10-25 08:21 UTC by sashav389

2022-10-26 17:06 UTC, GrEFeRFeeD commented
|File|Coverage [61.12%]|:green_apple:|
|:-|:-:|:-:|
|[StartDataLoader.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/c879edd73a5ddb167992954bb84cf13d66e7fd6e/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Finitialization%2FStartDataLoader.java)|100%|:green_apple:|
|[BookingLimitService.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/c879edd73a5ddb167992954bb84cf13d66e7fd6e/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Fbookinglimit%2FBookingLimitService.java)|100%|:green_apple:|
|[WeekService.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/c879edd73a5ddb167992954bb84cf13d66e7fd6e/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Fweek%2FWeekService.java)|89.74%|:green_apple:|
|[PeriodService.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/c879edd73a5ddb167992954bb84cf13d66e7fd6e/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Fperiod%2FPeriodService.java)|82.67%|:green_apple:|
|[InterviewerSlot.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/c879edd73a5ddb167992954bb84cf13d66e7fd6e/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Finterviewerslot%2FInterviewerSlot.java)|66.41%|:green_apple:|
|[Week.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/c879edd73a5ddb167992954bb84cf13d66e7fd6e/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Fweek%2FWeek.java)|61.25%|:green_apple:|
|[InterviewerSlotService.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/c879edd73a5ddb167992954bb84cf13d66e7fd6e/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Finterviewerslot%2FInterviewerSlotService.java)|55.32%|:green_apple:|
|[User.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/c879edd73a5ddb167992954bb84cf13d66e7fd6e/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Fuser%2FUser.java)|47.37%|:green_apple:|
|[Booking.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/c879edd73a5ddb167992954bb84cf13d66e7fd6e/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Fbooking%2FBooking.java)|45.61%|:green_apple:|
|[BookingLimit.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/c879edd73a5ddb167992954bb84cf13d66e7fd6e/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Fbookinglimit%2FBookingLimit.java)|36.9%|:green_apple:|
|[UserService.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/c879edd73a5ddb167992954bb84cf13d66e7fd6e/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Fuser%2FUserService.java)|28.57%|:green_apple:|
|[InterviewerController.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/c879edd73a5ddb167992954bb84cf13d66e7fd6e/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2FInterviewerController.java)|12%|:green_apple:|
|[InterviewerSlotDtoValidator.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/c879edd73a5ddb167992954bb84cf13d66e7fd6e/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Finterviewerslot%2FInterviewerSlotDtoValidator.java)|11.94%|:green_apple:|
|[SlotIsOverlappingException.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/c879edd73a5ddb167992954bb84cf13d66e7fd6e/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fexceptions%2FSlotIsOverlappingException.java)|0%|:x:|
|[SlotIsNotFoundException.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/c879edd73a5ddb167992954bb84cf13d66e7fd6e/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fexceptions%2FSlotIsNotFoundException.java)|0%|:x:|
|[InvalidInterviewerException.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/c879edd73a5ddb167992954bb84cf13d66e7fd6e/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fexceptions%2FInvalidInterviewerException.java)|0%|:x:|
|[InvalidDayOfWeekException.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/c879edd73a5ddb167992954bb84cf13d66e7fd6e/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fexceptions%2FInvalidDayOfWeekException.java)|0%|:x:|
|[CannotEditThisWeekException.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/c879edd73a5ddb167992954bb84cf13d66e7fd6e/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fexceptions%2FCannotEditThisWeekException.java)|0%|:x:|
|[InterviewerSlotDto.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/c879edd73a5ddb167992954bb84cf13d66e7fd6e/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2Fdtos%2FInterviewerSlotDto.java)|0%|:x:|

|Total Project Coverage|48.48%|:green_apple:|
|:-|:-:|:-:|

2022-10-26 19:54 UTC, GrEFeRFeeD commented
|File|Coverage [67.24%]|:green_apple:|
|:-|:-:|:-:|
|[StartDataLoader.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/ac31db6c410127040ba96e317273440a8efa51eb/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Finitialization%2FStartDataLoader.java)|100%|:green_apple:|
|[InvalidInterviewerException.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/ac31db6c410127040ba96e317273440a8efa51eb/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fexceptions%2FInvalidInterviewerException.java)|100%|:green_apple:|
|[InvalidDayOfWeekException.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/ac31db6c410127040ba96e317273440a8efa51eb/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fexceptions%2FInvalidDayOfWeekException.java)|100%|:green_apple:|
|[CannotEditThisWeekException.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/ac31db6c410127040ba96e317273440a8efa51eb/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fexceptions%2FCannotEditThisWeekException.java)|100%|:green_apple:|
|[BookingLimitService.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/ac31db6c410127040ba96e317273440a8efa51eb/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Fbookinglimit%2FBookingLimitService.java)|100%|:green_apple:|
|[WeekService.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/ac31db6c410127040ba96e317273440a8efa51eb/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Fweek%2FWeekService.java)|94.36%|:green_apple:|
|[PeriodService.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/ac31db6c410127040ba96e317273440a8efa51eb/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Fperiod%2FPeriodService.java)|82.67%|:green_apple:|
|[InterviewerSlot.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/ac31db6c410127040ba96e317273440a8efa51eb/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Finterviewerslot%2FInterviewerSlot.java)|68.75%|:green_apple:|
|[Week.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/ac31db6c410127040ba96e317273440a8efa51eb/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Fweek%2FWeek.java)|61.25%|:green_apple:|
|[InterviewerSlotService.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/ac31db6c410127040ba96e317273440a8efa51eb/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Finterviewerslot%2FInterviewerSlotService.java)|55.32%|:green_apple:|
|[InterviewerSlotDtoValidator.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/ac31db6c410127040ba96e317273440a8efa51eb/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Finterviewerslot%2FInterviewerSlotDtoValidator.java)|51.87%|:green_apple:|
|[User.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/ac31db6c410127040ba96e317273440a8efa51eb/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Fuser%2FUser.java)|47.37%|:green_apple:|
|[Booking.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/ac31db6c410127040ba96e317273440a8efa51eb/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Fbooking%2FBooking.java)|45.61%|:green_apple:|
|[BookingLimit.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/ac31db6c410127040ba96e317273440a8efa51eb/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Fbookinglimit%2FBookingLimit.java)|36.9%|:green_apple:|
|[UserService.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/ac31db6c410127040ba96e317273440a8efa51eb/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Fuser%2FUserService.java)|28.57%|:green_apple:|
|[InterviewerController.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/ac31db6c410127040ba96e317273440a8efa51eb/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2FInterviewerController.java)|12%|:green_apple:|
|[SlotIsOverlappingException.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/ac31db6c410127040ba96e317273440a8efa51eb/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fexceptions%2FSlotIsOverlappingException.java)|0%|:x:|
|[SlotIsNotFoundException.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/ac31db6c410127040ba96e317273440a8efa51eb/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fexceptions%2FSlotIsNotFoundException.java)|0%|:x:|
|[InterviewerSlotDto.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/ac31db6c410127040ba96e317273440a8efa51eb/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2Fdtos%2FInterviewerSlotDto.java)|0%|:x:|

|Total Project Coverage|51.3%|:green_apple:|
|:-|:-:|:-:|

2022-10-26 21:03 UTC, GrEFeRFeeD requested changes
Changes needed before applying your request.

2022-10-26 21:03 UTC, GrEFeRFeeD commented on src/main/java/com/intellias/intellistart/interviewplanning/model/week/WeekService.java
> +  private static  WeekRepository weekRepository;
Have you changed final to static keyword not in your Service?

2022-10-26 21:03 UTC, GrEFeRFeeD commented on src/test/java/com/intellias/intellistart/interviewplanning/controllers/InterviewerControllerTest.java
> +  //May be refactored ir deleted in the future
Better practice is not maintain commented code in production. You can save class as file to your PC or leave it in outer branch, this should not pass to main branch.

2022-10-26 21:59 UTC, GrEFeRFeeD commented
|File|Coverage [75.28%]|:green_apple:|
|:-|:-:|:-:|
|[StartDataLoader.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/59f7aa27889b1d463cee834c034d53136f064cc7/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Finitialization%2FStartDataLoader.java)|100%|:green_apple:|
|[InvalidInterviewerException.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/59f7aa27889b1d463cee834c034d53136f064cc7/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fexceptions%2FInvalidInterviewerException.java)|100%|:green_apple:|
|[InvalidDayOfWeekException.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/59f7aa27889b1d463cee834c034d53136f064cc7/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fexceptions%2FInvalidDayOfWeekException.java)|100%|:green_apple:|
|[CannotEditThisWeekException.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/59f7aa27889b1d463cee834c034d53136f064cc7/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fexceptions%2FCannotEditThisWeekException.java)|100%|:green_apple:|
|[BookingLimitService.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/59f7aa27889b1d463cee834c034d53136f064cc7/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Fbookinglimit%2FBookingLimitService.java)|100%|:green_apple:|
|[WeekService.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/59f7aa27889b1d463cee834c034d53136f064cc7/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Fweek%2FWeekService.java)|94.36%|:green_apple:|
|[InterviewerSlotService.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/59f7aa27889b1d463cee834c034d53136f064cc7/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Finterviewerslot%2FInterviewerSlotService.java)|84.85%|:green_apple:|
|[PeriodService.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/59f7aa27889b1d463cee834c034d53136f064cc7/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Fperiod%2FPeriodService.java)|82.67%|:green_apple:|
|[InterviewerSlotDtoValidator.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/59f7aa27889b1d463cee834c034d53136f064cc7/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Finterviewerslot%2FInterviewerSlotDtoValidator.java)|81.82%|:green_apple:|
|[InterviewerSlot.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/59f7aa27889b1d463cee834c034d53136f064cc7/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Finterviewerslot%2FInterviewerSlot.java)|77.34%|:green_apple:|
|[Week.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/59f7aa27889b1d463cee834c034d53136f064cc7/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Fweek%2FWeek.java)|61.25%|:green_apple:|
|[UserService.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/59f7aa27889b1d463cee834c034d53136f064cc7/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Fuser%2FUserService.java)|52.38%|:green_apple:|
|[InterviewerSlotDto.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/59f7aa27889b1d463cee834c034d53136f064cc7/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2Fdtos%2FInterviewerSlotDto.java)|47.66%|:green_apple:|
|[User.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/59f7aa27889b1d463cee834c034d53136f064cc7/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Fuser%2FUser.java)|47.37%|:green_apple:|
|[Booking.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/59f7aa27889b1d463cee834c034d53136f064cc7/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Fbooking%2FBooking.java)|45.61%|:green_apple:|
|[BookingLimit.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/59f7aa27889b1d463cee834c034d53136f064cc7/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Fbookinglimit%2FBookingLimit.java)|36.9%|:green_apple:|
|[InterviewerController.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/59f7aa27889b1d463cee834c034d53136f064cc7/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2FInterviewerController.java)|15.38%|:green_apple:|
|[SlotIsOverlappingException.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/59f7aa27889b1d463cee834c034d53136f064cc7/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fexceptions%2FSlotIsOverlappingException.java)|0%|:x:|
|[SlotIsNotFoundException.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/59f7aa27889b1d463cee834c034d53136f064cc7/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fexceptions%2FSlotIsNotFoundException.java)|0%|:x:|

|Total Project Coverage|55.01%|:green_apple:|
|:-|:-:|:-:|

2022-10-27 13:50 UTC, GrEFeRFeeD commented
|File|Coverage [75.91%]|:green_apple:|
|:-|:-:|:-:|
|[StartDataLoader.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/c8adb50a65fa0a6e2b93256da2ac2c27ac13ea0a/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Finitialization%2FStartDataLoader.java)|100%|:green_apple:|
|[InvalidInterviewerException.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/c8adb50a65fa0a6e2b93256da2ac2c27ac13ea0a/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fexceptions%2FInvalidInterviewerException.java)|100%|:green_apple:|
|[InvalidDayOfWeekException.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/c8adb50a65fa0a6e2b93256da2ac2c27ac13ea0a/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fexceptions%2FInvalidDayOfWeekException.java)|100%|:green_apple:|
|[CannotEditThisWeekException.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/c8adb50a65fa0a6e2b93256da2ac2c27ac13ea0a/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fexceptions%2FCannotEditThisWeekException.java)|100%|:green_apple:|
|[BookingLimitService.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/c8adb50a65fa0a6e2b93256da2ac2c27ac13ea0a/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Fbookinglimit%2FBookingLimitService.java)|100%|:green_apple:|
|[WeekService.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/c8adb50a65fa0a6e2b93256da2ac2c27ac13ea0a/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Fweek%2FWeekService.java)|94.36%|:green_apple:|
|[PeriodService.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/c8adb50a65fa0a6e2b93256da2ac2c27ac13ea0a/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Fperiod%2FPeriodService.java)|82.67%|:green_apple:|
|[InterviewerSlotDtoValidator.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/c8adb50a65fa0a6e2b93256da2ac2c27ac13ea0a/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Finterviewerslot%2FInterviewerSlotDtoValidator.java)|81.82%|:green_apple:|
|[InterviewerSlotService.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/c8adb50a65fa0a6e2b93256da2ac2c27ac13ea0a/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Finterviewerslot%2FInterviewerSlotService.java)|80.65%|:green_apple:|
|[InterviewerSlot.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/c8adb50a65fa0a6e2b93256da2ac2c27ac13ea0a/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Finterviewerslot%2FInterviewerSlot.java)|77.34%|:green_apple:|
|[InterviewerSlotDto.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/c8adb50a65fa0a6e2b93256da2ac2c27ac13ea0a/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2Fdtos%2FInterviewerSlotDto.java)|61.68%|:green_apple:|
|[Week.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/c8adb50a65fa0a6e2b93256da2ac2c27ac13ea0a/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Fweek%2FWeek.java)|61.25%|:green_apple:|
|[UserService.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/c8adb50a65fa0a6e2b93256da2ac2c27ac13ea0a/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Fuser%2FUserService.java)|52.38%|:green_apple:|
|[User.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/c8adb50a65fa0a6e2b93256da2ac2c27ac13ea0a/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Fuser%2FUser.java)|47.37%|:green_apple:|
|[Booking.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/c8adb50a65fa0a6e2b93256da2ac2c27ac13ea0a/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Fbooking%2FBooking.java)|45.61%|:green_apple:|
|[BookingLimit.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/c8adb50a65fa0a6e2b93256da2ac2c27ac13ea0a/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Fbookinglimit%2FBookingLimit.java)|36.9%|:green_apple:|
|[InterviewerController.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/c8adb50a65fa0a6e2b93256da2ac2c27ac13ea0a/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2FInterviewerController.java)|14.63%|:green_apple:|
|[SlotIsOverlappingException.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/c8adb50a65fa0a6e2b93256da2ac2c27ac13ea0a/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fexceptions%2FSlotIsOverlappingException.java)|0%|:x:|
|[SlotIsNotFoundException.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/c8adb50a65fa0a6e2b93256da2ac2c27ac13ea0a/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fexceptions%2FSlotIsNotFoundException.java)|0%|:x:|

|Total Project Coverage|55.31%|:green_apple:|
|:-|:-:|:-:|

2022-10-27 18:24 UTC, GrEFeRFeeD commented
|File|Coverage [76.46%]|:green_apple:|
|:-|:-:|:-:|
|[StartDataLoader.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/46efe0851ba38c1663177ea466a63e753dc8f759/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Finitialization%2FStartDataLoader.java)|100%|:green_apple:|
|[InvalidInterviewerException.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/46efe0851ba38c1663177ea466a63e753dc8f759/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fexceptions%2FInvalidInterviewerException.java)|100%|:green_apple:|
|[InvalidDayOfWeekException.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/46efe0851ba38c1663177ea466a63e753dc8f759/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fexceptions%2FInvalidDayOfWeekException.java)|100%|:green_apple:|
|[CannotEditThisWeekException.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/46efe0851ba38c1663177ea466a63e753dc8f759/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fexceptions%2FCannotEditThisWeekException.java)|100%|:green_apple:|
|[BookingLimitService.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/46efe0851ba38c1663177ea466a63e753dc8f759/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Fbookinglimit%2FBookingLimitService.java)|100%|:green_apple:|
|[WeekService.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/46efe0851ba38c1663177ea466a63e753dc8f759/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Fweek%2FWeekService.java)|94.39%|:green_apple:|
|[PeriodService.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/46efe0851ba38c1663177ea466a63e753dc8f759/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Fperiod%2FPeriodService.java)|82.67%|:green_apple:|
|[InterviewerSlotDtoValidator.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/46efe0851ba38c1663177ea466a63e753dc8f759/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Finterviewerslot%2FInterviewerSlotDtoValidator.java)|81.82%|:green_apple:|
|[InterviewerSlotService.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/46efe0851ba38c1663177ea466a63e753dc8f759/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Finterviewerslot%2FInterviewerSlotService.java)|80.65%|:green_apple:|
|[InterviewerSlot.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/46efe0851ba38c1663177ea466a63e753dc8f759/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Finterviewerslot%2FInterviewerSlot.java)|77.34%|:green_apple:|
|[Week.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/46efe0851ba38c1663177ea466a63e753dc8f759/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Fweek%2FWeek.java)|68.75%|:green_apple:|
|[InterviewerSlotDto.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/46efe0851ba38c1663177ea466a63e753dc8f759/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2Fdtos%2FInterviewerSlotDto.java)|61.68%|:green_apple:|
|[UserService.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/46efe0851ba38c1663177ea466a63e753dc8f759/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Fuser%2FUserService.java)|52.38%|:green_apple:|
|[User.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/46efe0851ba38c1663177ea466a63e753dc8f759/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Fuser%2FUser.java)|47.37%|:green_apple:|
|[Booking.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/46efe0851ba38c1663177ea466a63e753dc8f759/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Fbooking%2FBooking.java)|45.61%|:green_apple:|
|[BookingLimit.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/46efe0851ba38c1663177ea466a63e753dc8f759/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Fbookinglimit%2FBookingLimit.java)|36.9%|:green_apple:|
|[InterviewerController.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/46efe0851ba38c1663177ea466a63e753dc8f759/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2FInterviewerController.java)|12%|:green_apple:|
|[SlotIsOverlappingException.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/46efe0851ba38c1663177ea466a63e753dc8f759/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fexceptions%2FSlotIsOverlappingException.java)|0%|:x:|
|[SlotIsNotFoundException.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/46efe0851ba38c1663177ea466a63e753dc8f759/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fexceptions%2FSlotIsNotFoundException.java)|0%|:x:|

|Total Project Coverage|55.55%|:green_apple:|
|:-|:-:|:-:|

2022-10-28 05:59 UTC, GrEFeRFeeD commented
|File|Coverage [76.89%]|:green_apple:|
|:-|:-:|:-:|
|[StartDataLoader.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/4ae5f72684393fa5678804ecb31928053945c743/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Finitialization%2FStartDataLoader.java)|100%|:green_apple:|
|[InvalidInterviewerException.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/4ae5f72684393fa5678804ecb31928053945c743/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fexceptions%2FInvalidInterviewerException.java)|100%|:green_apple:|
|[InvalidDayOfWeekException.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/4ae5f72684393fa5678804ecb31928053945c743/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fexceptions%2FInvalidDayOfWeekException.java)|100%|:green_apple:|
|[CannotEditThisWeekException.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/4ae5f72684393fa5678804ecb31928053945c743/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fexceptions%2FCannotEditThisWeekException.java)|100%|:green_apple:|
|[BookingLimitService.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/4ae5f72684393fa5678804ecb31928053945c743/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Fbookinglimit%2FBookingLimitService.java)|100%|:green_apple:|
|[WeekService.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/4ae5f72684393fa5678804ecb31928053945c743/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Fweek%2FWeekService.java)|94.39%|:green_apple:|
|[PeriodService.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/4ae5f72684393fa5678804ecb31928053945c743/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Fperiod%2FPeriodService.java)|82.67%|:green_apple:|
|[InterviewerSlotDtoValidator.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/4ae5f72684393fa5678804ecb31928053945c743/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Finterviewerslot%2FInterviewerSlotDtoValidator.java)|81.82%|:green_apple:|
|[InterviewerSlotService.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/4ae5f72684393fa5678804ecb31928053945c743/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Finterviewerslot%2FInterviewerSlotService.java)|80.65%|:green_apple:|
|[InterviewerSlot.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/4ae5f72684393fa5678804ecb31928053945c743/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Finterviewerslot%2FInterviewerSlot.java)|77.34%|:green_apple:|
|[Week.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/4ae5f72684393fa5678804ecb31928053945c743/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Fweek%2FWeek.java)|65%|:green_apple:|
|[InterviewerSlotDto.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/4ae5f72684393fa5678804ecb31928053945c743/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2Fdtos%2FInterviewerSlotDto.java)|61.68%|:green_apple:|
|[User.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/4ae5f72684393fa5678804ecb31928053945c743/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Fuser%2FUser.java)|57.89%|:green_apple:|
|[UserService.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/4ae5f72684393fa5678804ecb31928053945c743/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Fuser%2FUserService.java)|52.38%|:green_apple:|
|[Booking.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/4ae5f72684393fa5678804ecb31928053945c743/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Fbooking%2FBooking.java)|45.61%|:green_apple:|
|[BookingLimit.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/4ae5f72684393fa5678804ecb31928053945c743/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Fbookinglimit%2FBookingLimit.java)|36.9%|:green_apple:|
|[InterviewerController.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/4ae5f72684393fa5678804ecb31928053945c743/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2FInterviewerController.java)|12%|:green_apple:|
|[SlotIsNotFoundException.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/4ae5f72684393fa5678804ecb31928053945c743/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fexceptions%2FSlotIsNotFoundException.java)|0%|:x:|

|Total Project Coverage|56.81%|:green_apple:|
|:-|:-:|:-:|

2022-10-28 06:01 UTC, GrEFeRFeeD approved these changes
Seems fine.

2022-10-28 08:32 UTC, sonnka approved these changes
Looks fine

2022-10-28 10:56 UTC, makskostyshen requested changes
Changes are needed. Test methods aren't checked yet.

2022-10-28 10:56 UTC, makskostyshen commented on src/main/java/com/intellias/intellistart/interviewplanning/model/interviewerslot/InterviewerSlot.java
>  }
?)

2022-10-28 10:56 UTC, makskostyshen commented on src/main/java/com/intellias/intellistart/interviewplanning/model/interviewerslot/InterviewerSlotDtoValidator.java
> +  public InterviewerSlot interviewerSlotValidateDto(InterviewerSlotDto interviewerSlotDto)
I don't like that your validator not only validates but also gives InterviewSlot object

2022-10-28 10:56 UTC, makskostyshen commented on src/main/java/com/intellias/intellistart/interviewplanning/model/interviewerslot/InterviewerSlotDtoValidator.java
> +    isCorrectDay(interviewerSlotDto.getDayOfWeek());
I'd rename such type of methods to "validate . . . ". If a method starts with "is", it should return boolean

2022-10-28 10:56 UTC, makskostyshen commented on src/main/java/com/intellias/intellistart/interviewplanning/controllers/dtos/InterviewerSlotDto.java
> +package com.intellias.intellistart.interviewplanning.controllers.dtos;
you should put this file to com/intellias/intellistart/interviewplanning/controllers/dto

2022-10-28 10:56 UTC, makskostyshen commented on src/main/java/com/intellias/intellistart/interviewplanning/model/interviewerslot/InterviewerSlotDtoValidator.java
> +    User user = isUserPresent(userOptional);
I'd remove this method and call exception explicitly if userOptional.isEmpty(). You have same naming of validation methods, that do the different job - some of them return something, some - don't

2022-10-28 10:56 UTC, makskostyshen commented on src/main/java/com/intellias/intellistart/interviewplanning/model/interviewerslot/InterviewerSlotDtoValidator.java
> +  public void isSlotOverlapping(Period period, Week week, User user, DayOfWeek dayOfWeek)
I'd change the method name. In the signature there is no slot

2022-10-28 10:56 UTC, makskostyshen commented on src/main/java/com/intellias/intellistart/interviewplanning/model/interviewerslot/InterviewerSlotDtoValidator.java
> +  }
I'd refactor that. In the week validation method you add day of week validation logic. You have validation for day of week, expand it with weekends check. Also, method's name canEditThisWeek, but is called both in updating and creating slots.

2022-10-28 10:56 UTC, makskostyshen commented on src/main/java/com/intellias/intellistart/interviewplanning/model/interviewerslot/InterviewerSlotService.java
> +  }
not crucial, but would be better to have the same namings and structure for similar methods with @guzeyarthur

2022-10-28 10:56 UTC, makskostyshen commented on src/main/java/com/intellias/intellistart/interviewplanning/model/period/PeriodService.java
> +  }
why did you add this method which is not called anywhere?

2022-10-28 19:12 UTC, sashav389 commented on src/main/java/com/intellias/intellistart/interviewplanning/controllers/InterviewerController.java
> +    }
done

2022-10-28 19:12 UTC, sashav389 commented on src/main/java/com/intellias/intellistart/interviewplanning/model/interviewerslot/InterviewerSlot.java
>  }
done

2022-10-28 19:13 UTC, sashav389 commented on src/main/java/com/intellias/intellistart/interviewplanning/model/interviewerslot/InterviewerSlotDtoValidator.java
> +    isCorrectDay(interviewerSlotDto.getDayOfWeek());
done

2022-10-28 19:14 UTC, sashav389 commented on src/main/java/com/intellias/intellistart/interviewplanning/controllers/dtos/InterviewerSlotDto.java
> +package com.intellias.intellistart.interviewplanning.controllers.dtos;
done

2022-10-28 19:14 UTC, sashav389 commented on src/main/java/com/intellias/intellistart/interviewplanning/model/interviewerslot/InterviewerSlotDtoValidator.java
> +  public void isSlotOverlapping(Period period, Week week, User user, DayOfWeek dayOfWeek)
done

2022-10-28 19:15 UTC, sashav389 commented on src/main/java/com/intellias/intellistart/interviewplanning/model/interviewerslot/InterviewerSlotService.java
> +  }
done

2022-10-28 19:17 UTC, sashav389 commented on src/main/java/com/intellias/intellistart/interviewplanning/model/interviewerslot/InterviewerSlotDtoValidator.java
> +  }
Did you mean to replace validation of day (if it before Friday 00:00) in WeekService?

2022-10-28 22:02 UTC, GrEFeRFeeD commented
|File|Coverage [76.11%]|:green_apple:|
|:-|:-:|:-:|
|[StartDataLoader.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/1914ec70f23d29f50b55e4d3fb45c64863f978c1/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Finitialization%2FStartDataLoader.java)|100%|:green_apple:|
|[InvalidInterviewerException.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/1914ec70f23d29f50b55e4d3fb45c64863f978c1/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fexceptions%2FInvalidInterviewerException.java)|100%|:green_apple:|
|[InvalidDayOfWeekException.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/1914ec70f23d29f50b55e4d3fb45c64863f978c1/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fexceptions%2FInvalidDayOfWeekException.java)|100%|:green_apple:|
|[CannotEditThisWeekException.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/1914ec70f23d29f50b55e4d3fb45c64863f978c1/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fexceptions%2FCannotEditThisWeekException.java)|100%|:green_apple:|
|[InterviewerSlotService.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/1914ec70f23d29f50b55e4d3fb45c64863f978c1/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Finterviewerslot%2FInterviewerSlotService.java)|100%|:green_apple:|
|[BookingLimitService.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/1914ec70f23d29f50b55e4d3fb45c64863f978c1/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Fbookinglimit%2FBookingLimitService.java)|100%|:green_apple:|
|[WeekService.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/1914ec70f23d29f50b55e4d3fb45c64863f978c1/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Fweek%2FWeekService.java)|94.39%|:green_apple:|
|[InterviewerSlotDtoValidator.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/1914ec70f23d29f50b55e4d3fb45c64863f978c1/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Finterviewerslot%2FInterviewerSlotDtoValidator.java)|80.23%|:green_apple:|
|[InterviewerSlot.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/1914ec70f23d29f50b55e4d3fb45c64863f978c1/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Finterviewerslot%2FInterviewerSlot.java)|77.34%|:green_apple:|
|[Week.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/1914ec70f23d29f50b55e4d3fb45c64863f978c1/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Fweek%2FWeek.java)|65%|:green_apple:|
|[InterviewerSlotDto.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/1914ec70f23d29f50b55e4d3fb45c64863f978c1/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2Fdto%2FInterviewerSlotDto.java)|62.18%|:green_apple:|
|[User.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/1914ec70f23d29f50b55e4d3fb45c64863f978c1/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Fuser%2FUser.java)|57.89%|:green_apple:|
|[UserService.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/1914ec70f23d29f50b55e4d3fb45c64863f978c1/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Fuser%2FUserService.java)|52.38%|:green_apple:|
|[Booking.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/1914ec70f23d29f50b55e4d3fb45c64863f978c1/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Fbooking%2FBooking.java)|45.61%|:green_apple:|
|[BookingLimit.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/1914ec70f23d29f50b55e4d3fb45c64863f978c1/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Fbookinglimit%2FBookingLimit.java)|36.9%|:green_apple:|
|[InterviewerController.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/1914ec70f23d29f50b55e4d3fb45c64863f978c1/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2FInterviewerController.java)|10.84%|:green_apple:|
|[SlotIsNotFoundException.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/1914ec70f23d29f50b55e4d3fb45c64863f978c1/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fexceptions%2FSlotIsNotFoundException.java)|0%|:x:|

|Total Project Coverage|56.62%|:green_apple:|
|:-|:-:|:-:|

2022-10-31 07:30 UTC, makskostyshen commented on src/main/java/com/intellias/intellistart/interviewplanning/model/interviewerslot/InterviewerSlotDtoValidator.java
> +  }
Yes, I understood the logic of this method. You were right, the structure is correct

2022-10-31 08:05 UTC, makskostyshen reviewed
I likw your changes. @guzeyarthur wanted to refactor the structure of his controller after mentor's review. If he will do it right now, it would be reasonable to make synchronous changes before your merge.

2022-10-31 19:34 UTC, makskostyshen approved these changes
looks fine

2022-10-31 19:37 UTC, merged