Implement candidate slot
GrEFeRFeeD/intellistart-java-2022-oneweek pull request #22
Opened 2022-10-26 01:32 UTC by guzeyarthur

2022-10-26 11:20 UTC, GrEFeRFeeD commented
|File|Coverage [46.88%]|:green_apple:|
|:-|:-:|:-:|
|[SlotNotFoundException.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/7174c2d2cd7d31a47c806e1e42aa426042bee945/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fexceptions%2FSlotNotFoundException.java)|100%|:green_apple:|
|[SlotIsOverlappingException.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/7174c2d2cd7d31a47c806e1e42aa426042bee945/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fexceptions%2FSlotIsOverlappingException.java)|100%|:green_apple:|
|[SlotIsBookedException.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/7174c2d2cd7d31a47c806e1e42aa426042bee945/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fexceptions%2FSlotIsBookedException.java)|100%|:green_apple:|
|[InvalidBoundariesException.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/7174c2d2cd7d31a47c806e1e42aa426042bee945/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fexceptions%2FInvalidBoundariesException.java)|100%|:green_apple:|
|[CandidateSlotService.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/7174c2d2cd7d31a47c806e1e42aa426042bee945/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Fcandidateslot%2FCandidateSlotService.java)|100%|:green_apple:|
|[CandidateSlotValidator.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/7174c2d2cd7d31a47c806e1e42aa426042bee945/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Fcandidateslot%2Fvalidation%2FCandidateSlotValidator.java)|98.94%|:green_apple:|
|[UserService.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/7174c2d2cd7d31a47c806e1e42aa426042bee945/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Fuser%2FUserService.java)|37.5%|:green_apple:|
|[JwtAuthenticationController.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/7174c2d2cd7d31a47c806e1e42aa426042bee945/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2FJwtAuthenticationController.java)|19.74%|:green_apple:|
|[CandidateController.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/7174c2d2cd7d31a47c806e1e42aa426042bee945/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2FCandidateController.java)|10.98%|:green_apple:|
|[CandidateSlotDto.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/7174c2d2cd7d31a47c806e1e42aa426042bee945/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2Fdto%2FCandidateSlotDto.java)|0%|:x:|
|[JwtRequest.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/7174c2d2cd7d31a47c806e1e42aa426042bee945/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2Fdto%2FJwtRequest.java)|0%|:x:|
|[JwtResponse.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/7174c2d2cd7d31a47c806e1e42aa426042bee945/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2Fdto%2FJwtResponse.java)|0%|:x:|
|[CandidateSlotsDto.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/7174c2d2cd7d31a47c806e1e42aa426042bee945/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2Fdto%2FCandidateSlotsDto.java)|0%|:x:|

|Total Project Coverage|55.29%|:green_apple:|
|:-|:-:|:-:|

2022-10-26 12:02 UTC, GrEFeRFeeD commented
|File|Coverage [46.85%]|:green_apple:|
|:-|:-:|:-:|
|[SlotNotFoundException.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/e33d81b602f018bf3e50caf7a56fb1b70ebacc66/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fexceptions%2FSlotNotFoundException.java)|100%|:green_apple:|
|[SlotIsOverlappingException.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/e33d81b602f018bf3e50caf7a56fb1b70ebacc66/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fexceptions%2FSlotIsOverlappingException.java)|100%|:green_apple:|
|[SlotIsBookedException.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/e33d81b602f018bf3e50caf7a56fb1b70ebacc66/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fexceptions%2FSlotIsBookedException.java)|100%|:green_apple:|
|[InvalidBoundariesException.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/e33d81b602f018bf3e50caf7a56fb1b70ebacc66/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fexceptions%2FInvalidBoundariesException.java)|100%|:green_apple:|
|[CandidateSlotService.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/e33d81b602f018bf3e50caf7a56fb1b70ebacc66/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Fcandidateslot%2FCandidateSlotService.java)|100%|:green_apple:|
|[CandidateSlotValidator.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/e33d81b602f018bf3e50caf7a56fb1b70ebacc66/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Fcandidateslot%2Fvalidation%2FCandidateSlotValidator.java)|98.99%|:green_apple:|
|[UserService.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/e33d81b602f018bf3e50caf7a56fb1b70ebacc66/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Fuser%2FUserService.java)|37.5%|:green_apple:|
|[JwtAuthenticationController.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/e33d81b602f018bf3e50caf7a56fb1b70ebacc66/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2FJwtAuthenticationController.java)|19.74%|:green_apple:|
|[CandidateController.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/e33d81b602f018bf3e50caf7a56fb1b70ebacc66/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2FCandidateController.java)|10.23%|:green_apple:|
|[CandidateSlotDto.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/e33d81b602f018bf3e50caf7a56fb1b70ebacc66/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2Fdto%2FCandidateSlotDto.java)|0%|:x:|
|[JwtRequest.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/e33d81b602f018bf3e50caf7a56fb1b70ebacc66/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2Fdto%2FJwtRequest.java)|0%|:x:|
|[JwtResponse.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/e33d81b602f018bf3e50caf7a56fb1b70ebacc66/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2Fdto%2FJwtResponse.java)|0%|:x:|
|[CandidateSlotsDto.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/e33d81b602f018bf3e50caf7a56fb1b70ebacc66/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2Fdto%2FCandidateSlotsDto.java)|0%|:x:|

|Total Project Coverage|55.26%|:green_apple:|
|:-|:-:|:-:|

2022-10-26 13:31 UTC, makskostyshen requested changes

2022-10-26 13:31 UTC, makskostyshen commented on src/main/java/com/intellias/intellistart/interviewplanning/model/candidateslot/validation/CandidateSlotValidator.java
> +  }
I'd rename this method to "validateCreation". It's not explicit whether it creates or validates

2022-10-26 13:31 UTC, makskostyshen commented on src/main/java/com/intellias/intellistart/interviewplanning/model/candidateslot/validation/CandidateSlotValidator.java
> +  }
Here rename is needed to

2022-10-26 13:31 UTC, makskostyshen commented on src/main/java/com/intellias/intellistart/interviewplanning/controllers/CandidateController.java
> +  }
Why do you implement updating slots if it's not in the task?

2022-10-26 13:38 UTC, GrEFeRFeeD commented on src/main/java/com/intellias/intellistart/interviewplanning/controllers/CandidateController.java
> +  }
Bad task description, this detail was mentioned orally. Create-update operations are almost identical so the task implied implementing the creation of a slot as well as updating it.

2022-10-26 19:16 UTC, sonnka commented
Everything is great, but it would be better, as written in the comment above, to add empty lines to improve the readability of the code

2022-10-26 20:43 UTC, GrEFeRFeeD reviewed
Except already meantioned problems, everything seems fine.

2022-10-26 20:43 UTC, GrEFeRFeeD commented on src/main/java/com/intellias/intellistart/interviewplanning/model/candidateslot/CandidateSlotService.java
> +  }
As an option you can reuse your create() method instead of calling repository save() method.

2022-10-26 22:41 UTC, GrEFeRFeeD commented
|File|Coverage [46.36%]|:green_apple:|
|:-|:-:|:-:|
|[SlotNotFoundException.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/2a81a8076798bc2472a1d45728652e9a1fbf6536/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fexceptions%2FSlotNotFoundException.java)|100%|:green_apple:|
|[SlotIsOverlappingException.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/2a81a8076798bc2472a1d45728652e9a1fbf6536/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fexceptions%2FSlotIsOverlappingException.java)|100%|:green_apple:|
|[SlotIsBookedException.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/2a81a8076798bc2472a1d45728652e9a1fbf6536/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fexceptions%2FSlotIsBookedException.java)|100%|:green_apple:|
|[InvalidBoundariesException.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/2a81a8076798bc2472a1d45728652e9a1fbf6536/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fexceptions%2FInvalidBoundariesException.java)|100%|:green_apple:|
|[CandidateSlotService.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/2a81a8076798bc2472a1d45728652e9a1fbf6536/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Fcandidateslot%2FCandidateSlotService.java)|100%|:green_apple:|
|[CandidateSlotValidator.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/2a81a8076798bc2472a1d45728652e9a1fbf6536/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Fcandidateslot%2Fvalidation%2FCandidateSlotValidator.java)|98.97%|:green_apple:|
|[UserService.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/2a81a8076798bc2472a1d45728652e9a1fbf6536/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Fuser%2FUserService.java)|37.5%|:green_apple:|
|[JwtAuthenticationController.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/2a81a8076798bc2472a1d45728652e9a1fbf6536/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2FJwtAuthenticationController.java)|19.74%|:green_apple:|
|[CandidateController.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/2a81a8076798bc2472a1d45728652e9a1fbf6536/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2FCandidateController.java)|10.23%|:green_apple:|
|[CandidateSlotDto.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/2a81a8076798bc2472a1d45728652e9a1fbf6536/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2Fdto%2FCandidateSlotDto.java)|0%|:x:|
|[JwtRequest.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/2a81a8076798bc2472a1d45728652e9a1fbf6536/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2Fdto%2FJwtRequest.java)|0%|:x:|
|[JwtResponse.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/2a81a8076798bc2472a1d45728652e9a1fbf6536/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2Fdto%2FJwtResponse.java)|0%|:x:|
|[CandidateSlotsDto.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/2a81a8076798bc2472a1d45728652e9a1fbf6536/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2Fdto%2FCandidateSlotsDto.java)|0%|:x:|

|Total Project Coverage|55.21%|:green_apple:|
|:-|:-:|:-:|

2022-10-26 22:46 UTC, GrEFeRFeeD commented
|File|Coverage [46.36%]|:green_apple:|
|:-|:-:|:-:|
|[SlotNotFoundException.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/d9b4817f04dea2afbe6f8002168e169ba3f2ae38/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fexceptions%2FSlotNotFoundException.java)|100%|:green_apple:|
|[SlotIsOverlappingException.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/d9b4817f04dea2afbe6f8002168e169ba3f2ae38/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fexceptions%2FSlotIsOverlappingException.java)|100%|:green_apple:|
|[SlotIsBookedException.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/d9b4817f04dea2afbe6f8002168e169ba3f2ae38/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fexceptions%2FSlotIsBookedException.java)|100%|:green_apple:|
|[InvalidBoundariesException.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/d9b4817f04dea2afbe6f8002168e169ba3f2ae38/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fexceptions%2FInvalidBoundariesException.java)|100%|:green_apple:|
|[CandidateSlotService.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/d9b4817f04dea2afbe6f8002168e169ba3f2ae38/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Fcandidateslot%2FCandidateSlotService.java)|100%|:green_apple:|
|[CandidateSlotValidator.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/d9b4817f04dea2afbe6f8002168e169ba3f2ae38/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Fcandidateslot%2Fvalidation%2FCandidateSlotValidator.java)|98.97%|:green_apple:|
|[UserService.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/d9b4817f04dea2afbe6f8002168e169ba3f2ae38/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Fuser%2FUserService.java)|37.5%|:green_apple:|
|[JwtAuthenticationController.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/d9b4817f04dea2afbe6f8002168e169ba3f2ae38/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2FJwtAuthenticationController.java)|19.74%|:green_apple:|
|[CandidateController.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/d9b4817f04dea2afbe6f8002168e169ba3f2ae38/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2FCandidateController.java)|10.23%|:green_apple:|
|[CandidateSlotDto.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/d9b4817f04dea2afbe6f8002168e169ba3f2ae38/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2Fdto%2FCandidateSlotDto.java)|0%|:x:|
|[JwtRequest.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/d9b4817f04dea2afbe6f8002168e169ba3f2ae38/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2Fdto%2FJwtRequest.java)|0%|:x:|
|[JwtResponse.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/d9b4817f04dea2afbe6f8002168e169ba3f2ae38/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2Fdto%2FJwtResponse.java)|0%|:x:|
|[CandidateSlotsDto.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/d9b4817f04dea2afbe6f8002168e169ba3f2ae38/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2Fdto%2FCandidateSlotsDto.java)|0%|:x:|

|Total Project Coverage|55.21%|:green_apple:|
|:-|:-:|:-:|

2022-10-27 18:32 UTC, sashav389 approved these changes

2022-10-27 19:03 UTC, makskostyshen requested changes
good job) I have written some small questions

2022-10-27 19:03 UTC, makskostyshen commented on src/main/java/com/intellias/intellistart/interviewplanning/model/candidateslot/validation/CandidateSlotValidator.java
> +  public void validateUpdates(CandidateSlot candidateSlot, Long id)
I'd say validateUpdation) :art:

2022-10-27 20:05 UTC, guzeyarthur commented on src/main/java/com/intellias/intellistart/interviewplanning/controllers/CandidateController.java
> +    CandidateSlot candidateSlot = getCandidateSlotFromDto(request);
During the object conversion, there is a call to third-party services that validate. Also after conversion, the CandidateSlot object is validated in the candidateSlotValidator

2022-10-27 20:07 UTC, guzeyarthur commented on src/main/java/com/intellias/intellistart/interviewplanning/model/candidateslot/validation/CandidateSlotValidator.java
> +  public void validateUpdates(CandidateSlot candidateSlot, Long id)
I'll fix that.

2022-10-27 20:10 UTC, makskostyshen commented on src/main/java/com/intellias/intellistart/interviewplanning/controllers/CandidateController.java
> +    CandidateSlot candidateSlot = getCandidateSlotFromDto(request);
yes, understood, thanks

2022-10-27 20:15 UTC, GrEFeRFeeD commented
|File|Coverage [46.36%]|:green_apple:|
|:-|:-:|:-:|
|[SlotNotFoundException.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/21a0e0b4cd7cef846a7655afdf6c8348b800e59b/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fexceptions%2FSlotNotFoundException.java)|100%|:green_apple:|
|[SlotIsOverlappingException.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/21a0e0b4cd7cef846a7655afdf6c8348b800e59b/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fexceptions%2FSlotIsOverlappingException.java)|100%|:green_apple:|
|[SlotIsBookedException.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/21a0e0b4cd7cef846a7655afdf6c8348b800e59b/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fexceptions%2FSlotIsBookedException.java)|100%|:green_apple:|
|[InvalidBoundariesException.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/21a0e0b4cd7cef846a7655afdf6c8348b800e59b/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fexceptions%2FInvalidBoundariesException.java)|100%|:green_apple:|
|[CandidateSlotService.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/21a0e0b4cd7cef846a7655afdf6c8348b800e59b/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Fcandidateslot%2FCandidateSlotService.java)|100%|:green_apple:|
|[CandidateSlotValidator.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/21a0e0b4cd7cef846a7655afdf6c8348b800e59b/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Fcandidateslot%2Fvalidation%2FCandidateSlotValidator.java)|98.97%|:green_apple:|
|[UserService.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/21a0e0b4cd7cef846a7655afdf6c8348b800e59b/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Fuser%2FUserService.java)|37.5%|:green_apple:|
|[JwtAuthenticationController.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/21a0e0b4cd7cef846a7655afdf6c8348b800e59b/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2FJwtAuthenticationController.java)|19.74%|:green_apple:|
|[CandidateController.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/21a0e0b4cd7cef846a7655afdf6c8348b800e59b/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2FCandidateController.java)|10.23%|:green_apple:|
|[CandidateSlotDto.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/21a0e0b4cd7cef846a7655afdf6c8348b800e59b/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2Fdto%2FCandidateSlotDto.java)|0%|:x:|
|[JwtRequest.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/21a0e0b4cd7cef846a7655afdf6c8348b800e59b/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2Fdto%2FJwtRequest.java)|0%|:x:|
|[JwtResponse.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/21a0e0b4cd7cef846a7655afdf6c8348b800e59b/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2Fdto%2FJwtResponse.java)|0%|:x:|
|[CandidateSlotsDto.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/21a0e0b4cd7cef846a7655afdf6c8348b800e59b/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2Fdto%2FCandidateSlotsDto.java)|0%|:x:|

|Total Project Coverage|54.99%|:green_apple:|
|:-|:-:|:-:|

2022-10-27 20:19 UTC, makskostyshen approved these changes
awesome)

2022-10-27 22:28 UTC, merged