Fix interviewer controller and refactoring it
GrEFeRFeeD/intellistart-java-2022-oneweek pull request #52
Opened 2022-11-10 09:53 UTC by sashav389

2022-11-10 09:54 UTC, GrEFeRFeeD commented
|File|Coverage [34.07%]|:green_apple:|
|:-|:-:|:-:|
|[InterviewerSlotDtoValidator.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/fc72f6a949c999bf163dc306a543155a4e5eceec/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Finterviewerslot%2FInterviewerSlotDtoValidator.java)|40.14%|:green_apple:|
|[InterviewerController.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/fc72f6a949c999bf163dc306a543155a4e5eceec/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2FInterviewerController.java)|14.12%|:green_apple:|

|Total Project Coverage|53.11%|:green_apple:|
|:-|:-:|:-:|

2022-11-10 20:19 UTC, sonnka approved these changes

2022-11-10 21:46 UTC, GrEFeRFeeD commented
|File|Coverage [34.07%]|:green_apple:|
|:-|:-:|:-:|
|[InterviewerSlotDtoValidator.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/107026fef1d5ca2bd60d1a8fa1278747fefdd892/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Finterviewerslot%2FInterviewerSlotDtoValidator.java)|40.14%|:green_apple:|
|[InterviewerController.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/107026fef1d5ca2bd60d1a8fa1278747fefdd892/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2FInterviewerController.java)|14.12%|:green_apple:|

|Total Project Coverage|54.21%|:green_apple:|
|:-|:-:|:-:|

2022-11-10 21:52 UTC, GrEFeRFeeD approved these changes
Good work.

2022-11-10 21:52 UTC, GrEFeRFeeD commented
|File|Coverage [42.17%]|:green_apple:|
|:-|:-:|:-:|
|[PeriodValidator.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/1e43c45a2450c5072b5cd5f82cee7fcfac4ca7aa/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Fperiod%2Fservices%2Fvalidation%2FPeriodValidator.java)|100%|:green_apple:|
|[InterviewerSlotDtoValidator.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/1e43c45a2450c5072b5cd5f82cee7fcfac4ca7aa/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Finterviewerslot%2FInterviewerSlotDtoValidator.java)|40.14%|:green_apple:|
|[InterviewerController.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/1e43c45a2450c5072b5cd5f82cee7fcfac4ca7aa/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2FInterviewerController.java)|14.12%|:green_apple:|

|Total Project Coverage|54.21%|:green_apple:|
|:-|:-:|:-:|

2022-11-11 11:35 UTC, makskostyshen requested changes
Generally okay. Small method names questions

2022-11-11 11:35 UTC, makskostyshen commented on src/main/java/com/intellias/intellistart/interviewplanning/controllers/InterviewerController.java
> +        .interviewerSlotValidateDtoAndCreate(interviewerSlotDto, authentication, interviewerId);
I'd rename method to just validateAndCreate

2022-11-11 11:35 UTC, makskostyshen commented on src/main/java/com/intellias/intellistart/interviewplanning/controllers/InterviewerController.java
> +        .interviewerSlotValidateDtoAndUpdate(interviewerSlotDto, authentication, interviewerId,
I'd rename method to just validateAndUpdate

2022-11-11 12:02 UTC, GrEFeRFeeD commented
|File|Coverage [42.17%]|:green_apple:|
|:-|:-:|:-:|
|[PeriodValidator.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/56480a0b911a96bb6177d1fec16ae0c9c0fbdbda/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Fperiod%2Fservices%2Fvalidation%2FPeriodValidator.java)|100%|:green_apple:|
|[InterviewerSlotDtoValidator.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/56480a0b911a96bb6177d1fec16ae0c9c0fbdbda/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Finterviewerslot%2FInterviewerSlotDtoValidator.java)|40.14%|:green_apple:|
|[InterviewerController.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/56480a0b911a96bb6177d1fec16ae0c9c0fbdbda/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2FInterviewerController.java)|14.12%|:green_apple:|

|Total Project Coverage|54.21%|:green_apple:|
|:-|:-:|:-:|

2022-11-11 12:07 UTC, makskostyshen approved these changes
Okay)

2022-11-11 12:10 UTC, merged