Implement BookingLimitService
GrEFeRFeeD/intellistart-java-2022-oneweek pull request #53
Opened 2022-11-10 19:45 UTC by sonnka

2022-11-10 20:12 UTC, GrEFeRFeeD commented
|File|Coverage [37.53%]|:green_apple:|
|:-|:-:|:-:|
|[InvalidBookingLimitException.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/f96f91f2482cc593703d0f6811973bcff9a68316/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fexceptions%2FInvalidBookingLimitException.java)|100%|:green_apple:|
|[BookingLimitService.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/f96f91f2482cc593703d0f6811973bcff9a68316/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Fbookinglimit%2FBookingLimitService.java)|89.47%|:green_apple:|
|[InterviewerController.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/f96f91f2482cc593703d0f6811973bcff9a68316/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2FInterviewerController.java)|8.33%|:x:|
|[BookingLimitDto.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/f96f91f2482cc593703d0f6811973bcff9a68316/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2Fdto%2FBookingLimitDto.java)|0%|:x:|

|Total Project Coverage|56.82%|:green_apple:|
|:-|:-:|:-:|

2022-11-11 08:06 UTC, GrEFeRFeeD requested changes
Incorrect business logic for now.

2022-11-11 08:06 UTC, GrEFeRFeeD commented on src/main/java/com/intellias/intellistart/interviewplanning/model/bookinglimit/BookingLimitService.java
> +    while (weekNum > 0) {
You don't change your bookingLimit inside the cycle. Should findById be inside of cycle, not before?

2022-11-11 08:06 UTC, GrEFeRFeeD commented on src/main/java/com/intellias/intellistart/interviewplanning/controllers/InterviewerController.java
> +  @PostMapping("/interviewers/{interviewerId}/booking-limit")
`booking-limits` instead of `booking-limit` would be preferable for REST endpoints.

2022-11-11 08:06 UTC, GrEFeRFeeD commented on src/main/java/com/intellias/intellistart/interviewplanning/model/bookinglimit/BookingLimitService.java
> +    User user = userService.getUserById(interviewerId)
What if we pass Coordinator here? We don't need to find Coordinator's bookingLimit. Add simple check & exception for it.

2022-11-11 08:06 UTC, GrEFeRFeeD commented on src/main/java/com/intellias/intellistart/interviewplanning/model/bookinglimit/BookingLimitService.java
> +  private BookingLimit createInfiniteBookingLimit(User user, Week week) {
Should we save bLimit obj with 0 value to the DB or returning just the bookingLimit object without saving would be enough?

2022-11-11 09:25 UTC, GrEFeRFeeD commented
|File|Coverage [38.95%]|:green_apple:|
|:-|:-:|:-:|
|[InvalidBookingLimitException.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/0848934d071e5f614be6996b932103faf06c5686/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fexceptions%2FInvalidBookingLimitException.java)|100%|:green_apple:|
|[NotInterviewerException.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/0848934d071e5f614be6996b932103faf06c5686/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fexceptions%2FNotInterviewerException.java)|100%|:green_apple:|
|[BookingLimitService.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/0848934d071e5f614be6996b932103faf06c5686/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Fbookinglimit%2FBookingLimitService.java)|87.59%|:green_apple:|
|[InterviewerController.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/0848934d071e5f614be6996b932103faf06c5686/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2FInterviewerController.java)|8.33%|:x:|
|[BookingLimitDto.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/0848934d071e5f614be6996b932103faf06c5686/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2Fdto%2FBookingLimitDto.java)|0%|:x:|

|Total Project Coverage|57.76%|:green_apple:|
|:-|:-:|:-:|

2022-11-11 10:42 UTC, GrEFeRFeeD approved these changes
Great work.

2022-11-11 12:06 UTC, makskostyshen requested changes
I like the structure of your code in general. But to my mind, it's better to check the existence of object by given id right away, not pass id to other methods and classes and check it there.

2022-11-11 12:06 UTC, makskostyshen commented on src/main/java/com/intellias/intellistart/interviewplanning/model/bookinglimit/BookingLimitService.java
> +  private BookingLimit createInfiniteBookingLimit(User user, Week week) {
I think we should create a really infinite booking limit. not null. For example: 63 - max possiible number of interviews for week. I'd save INFINITE_INTERVIEWS_NUMBER  as a constant.

2022-11-11 12:59 UTC, sashav389 approved these changes

2022-11-11 19:14 UTC, GrEFeRFeeD commented
|File|Coverage [44.71%]|:green_apple:|
|:-|:-:|:-:|
|[InvalidBookingLimitException.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/a681952b36114bcccf213b4c334b8baf0fe3cf52/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fexceptions%2FInvalidBookingLimitException.java)|100%|:green_apple:|
|[NotInterviewerException.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/a681952b36114bcccf213b4c334b8baf0fe3cf52/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fexceptions%2FNotInterviewerException.java)|100%|:green_apple:|
|[BookingLimitService.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/a681952b36114bcccf213b4c334b8baf0fe3cf52/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Fbookinglimit%2FBookingLimitService.java)|87.59%|:green_apple:|
|[InterviewerController.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/a681952b36114bcccf213b4c334b8baf0fe3cf52/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2FInterviewerController.java)|11.45%|:green_apple:|
|[BookingLimitDto.java](https://github.com/GrEFeRFeeD/intellistart-java-2022-oneweek/blob/a681952b36114bcccf213b4c334b8baf0fe3cf52/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2Fdto%2FBookingLimitDto.java)|0%|:x:|

|Total Project Coverage|55.64%|:green_apple:|
|:-|:-:|:-:|

2022-11-14 16:37 UTC, makskostyshen requested changes
Great. Only one little change would be preferable.

2022-11-14 16:37 UTC, makskostyshen commented on src/main/java/com/intellias/intellistart/interviewplanning/controllers/InterviewerController.java
> +        .orElseThrow(InvalidInterviewerException::new);
We decided to throw an exception right after we didn't find something in the database. It's better to throw it in getUserById(interviewerId) UserService method

2022-11-14 19:18 UTC, makskostyshen approved these changes

2022-11-14 19:19 UTC, merged